version: "3.9"
services:
  message-broker:
    hostname: rabbit_mq
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 5000:15672
    networks:
      - demokit
    restart: on-failure
networks:
  demokit:
    name: demokit
