version: "3.9"
services:
  message-broker:
    hostname: rabbit_mq
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - 5000:15672
      - 5672:5672
    networks:
      - demokit
        #restart: on-failure

  registration-service:
    hostname: registration_service
    image: demokti-registration-service:latest
    container_name: registration-service
    ports:
      - 4000:4000
    networks:
      - demokit

networks:
  demokit:
    name: demokit
  demokit-infra:
    name: demokit-infra
